const COMET_URL = process.env.VUE_APP_COMET
const FIWARE_SERVICE = 'dbs'
const FIWARE_SERVICE_PATH = '/'
const COMET_ENTITY_TYPE = process.env.VUE_APP_COMET_ENTITY_TYPE
const COMET_ENTITY_ID = process.env.VUE_APP_COMET_ENTITY_ID
const COMET_ENTITY_TYPE_2 = process.env.VUE_APP_COMET_ENTITY_TYPE_2
const COMET_ENTITY_ID_2 = process.env.VUE_APP_COMET_ENTITY_ID_2
const GRAPH1_LEFT = 'air_temp'
const GRAPH1_LEFT_NAME = '温度'
const GRAPH1_RIGHT = 'air_humid'
const GRAPH1_RIGHT_NAME = '湿度'
const GRAPH2 = 'illuminance'
const GRAPH2_NAME = '照度'
const GUIDE_1 = 'rgba(220, 100, 20, 1.0)'
const GUIDE_2 = 'rgba(60, 160, 220, 1.0)'
const GUIDE_3 = 'rgba(160, 60, 220, 1.0)'
const YAXIS_1 = 'y1'
const YAXIS_2 = 'y2'
const LEFT = 'left'
const RIGHT = 'right'

export default {
  COMET_URL: COMET_URL,
  FIWARE_SERVICE: FIWARE_SERVICE,
  FIWARE_SERVICE_PATH: FIWARE_SERVICE_PATH,
  COMET_ENTITY_TYPE: COMET_ENTITY_TYPE,
  COMET_ENTITY_ID: COMET_ENTITY_ID,
  COMET_ENTITY_TYPE_2: COMET_ENTITY_TYPE_2,
  COMET_ENTITY_ID_2: COMET_ENTITY_ID_2,
  GRAPH1_LEFT: GRAPH1_LEFT,
  GRAPH1_LEFT_NAME: GRAPH1_LEFT_NAME,
  GRAPH1_RIGHT: GRAPH1_RIGHT,
  GRAPH1_RIGHT_NAME: GRAPH1_RIGHT_NAME,
  GRAPH2: GRAPH2,
  GRAPH2_NAME: GRAPH2_NAME,
  GUIDE_1: GUIDE_1,
  GUIDE_2: GUIDE_2,
  GUIDE_3: GUIDE_3,
  YAXIS_1: YAXIS_1,
  YAXIS_2: YAXIS_2,
  LEFT: LEFT,
  RIGHT: RIGHT,
}
